---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cwb::default]
      - recipe[sysbench::default]
    attributes:
      benchmark:
        ssh_username: vagrant
        logging_enabled: true
      sysbench:
        cli_options:
          cpu-max-prime: 3000