---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.8.1

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[perfmon::default]
    attributes:
