---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cwb::default]
      - recipe[sysbench-monitored::default]
    attributes:
      benchmark:
        ssh_username: vagrant
        logging_enabled: true
      sysbench:
        cli_options:
          cpu-max-prime: 20000
        metrics:
          execution_time: execution_time
          cpu: cpu
      sysbench-monitored:
        runtime: 40
        sar_interval: 1
        sleeptime: 10