---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cwb::default]
      - recipe[fio::default]
    attributes:
      benchmark:
        ssh_username: vagrant
        redirect_io: true
      fio:
        config:
          size: 40m